### ISSUE TITLE
VSCode extension fail test

### ISSUE THREAD

**Issue by anarion80** [atc-net/atc-dsc-configurations#12]
Great work with this repository, very useful!

I think there is an issue with 
https://github.com/atc-net/atc-winget-configurations/blob/80aef2d943af4b8bd7e75ac9c343f18e1331cf5d/configurations/configuration.dsc.yaml#L140

It fails:

```
Apply :: Script [VisualStudioCode Extensions]
  The configuration unit failed while attempting to test the current system state.
System.InvalidOperationException: The test script threw an error.
 ---> System.Management.Automation.CommandNotFoundException: The term 'code' is not recognized as a name of a cmdlet, function, script file, or executable program.…
<See the log file for additional details>
```

Looks like we need the env reload for test as well, because the test already executed the newly installed `code`:
```yaml
TestScript: |
          # Ignore deprecation warnings & reload path
          $env:NODE_OPTIONS="--no-deprecation"
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
```

**Comment by perkops** [comment]
Hi @anarion80,

I tested on my VM, and cannot get it to fail.

Tried in both Windows Powershell v. 5.1.22621.3880
Aswell as Powershell Core v. 7.4.5

Down-scaled version with only Npp, VSCode + extensions:
![image](https://github.com/user-attachments/assets/b254aa18-a888-4be3-9a1a-9f3d99fbcea2)

Full run (where wsl failed though - but not VSCode)
![image](https://github.com/user-attachments/assets/9994c3da-6db8-4d79-8521-5a73dea74c33)

wsl succeeded on second attempt ( a popup i had to approve occured this time, apparently i didnt see it before, because i went away from the pc while running the script)
![image](https://github.com/user-attachments/assets/da1717f6-1a67-4690-a4c0-de173079586c)

**Comment by anarion80** [comment]
Thanks. When running via `setup.ps1` and then `Run Script` then it indeed works.

I did `winget configure .\configuration.dsc.yaml --accept-configuration-agreements` and this seems to run Test first Then Run and therefore fails.

**Comment by perkops** [comment]
> Thanks. When running via `setup.ps1` and then `Run Script` then it indeed works.
> 
> I did `winget configure .\configuration.dsc.yaml --accept-configuration-agreements` and this seems to run Test first Then Run and therefore fails.

Thank you - now i got the error aswell - added a fix now :)

Note: configure doesnt run test - that would be the command "configure test" :)
